### ISSUE TITLE
--bootstrap-version is not considered?

### ISSUE THREAD

**Issue by tknerr** [fnichol/knife-server#23]
I was just trying to bootstrap an older version of chef server using this command:

```
knife server bootstrap standalone --ssh-user vagrant --ssh-password vagrant --node-name c16057-ihub.local --host 33.33.67.70 --bootstrap-version 10.16.2 --webui-password chefchef`
```

However, the `--bootstrap-version` seemed to have no effect and Chef Server 10.18.2 was installed instead.

In `chef-server-debian.erb` I noticed that the bootstrap version is not passed to `apt-get install`: 
https://github.com/fnichol/knife-server/blob/master/lib/chef/knife/bootstrap/chef-server-debian.erb#L85

Is it missing from here or is the chef version enforced by some other mechanism?

Cheers, Torben

**Comment by tknerr** [comment]
and similarly in the omnibus [bootstrap template L#68](https://github.com/fnichol/knife-server/blob/omnibus/lib/chef/knife/bootstrap/omnibus-debian.erb#L68) it should be 

`curl -L https://www.opscode.com/chef/install.sh | bash -s -- -v <bootstrap_version>`

shouldn't it?

**Comment by erikh** [comment]
yep, fun fact, I found out the hard way last night when opscode released chef 11 and broke some zone auto-bootstrap stuff I was working against.

I can probably fix this tomorrow.

**Comment by erikh** [comment]
@fnichol don't release until I fix this, I don't think it'll be complicated and I'll figure out the other issue too.

**Comment by erikh** [comment]
turns out.. it's complicated. I'll explain more in #22 but I don't think we'll be able to fix this without some further discussion.

**Comment by fnichol** [comment]
There should be better support for the `---bootstrap-version` flag now that 1.0.0 is out the door. There are now a few uses for this flag:
- (unset) - this will default to installing a Chef 11 server from Omnibus packages using the latest stable release, similar to filling out the form on http://www.opscode.com/chef/install/ (click the "Chef Server" tab).
- `"11.*"` - this will select the specific Omnibus package version you want installed. As a sidenote, using the `--prerelease` flag in combination with `--bootstrap-version` should allow you to get pre-release packages available through Opscode's omnitruck download service.
- `"10"` or `"10.*"` - this will choose a Chef 10 bootstrapping template (under `lib/knife/server/bootstrap/chef10`)

Unfortunately due to the way the Chef 10 server is delivered (by a solo chef run in RHEL and apt reposity in Debian/Ubuntu) it's very hard to specify the exact version of Chef Server v10.

Hopefully this closes out this issue. If I've misunderstood, please reopen, thanks!

**Comment by tknerr** [comment]
Thanks! Will give it a try and let you know. Cheers, Torben
