### ISSUE TITLE
Chef Server 10 not installing

### ISSUE THREAD

**Issue by vovans82** [fnichol/knife-server#45]
Waiting for sshd...done
Can not find bootstrap definition for chef10/omnibus
ERROR: Errno::ENOENT: No such file or directory

Can you please tell me what I'm doing wrong. 

This is what I'm running: 
knife server bootstrap ec2 --node-name infra-chef-server --ssh-user ubuntu --flavor m1.large --image ami-de0d9eb7 --region us-east-1 --bootstrap-version 10 --ssh-key prod-chef --identity-file ~/.ssh/prod-aws -c inf-knife.rb

Also this uses the Ubuntu server. 

Is there a way to do the same thing with CentOS 6 instance ? 

Thanks

**Comment by fnichol** [comment]
@vovans82 Sorry if this response comes way too late, but I think I see what's happening; it looks like you'd also need the `--platform debian` flag added to the command above making it:

``` bash
knife server bootstrap ec2 --node-name infra-chef-server --ssh-user ubuntu --flavor m1.large --image ami-de0d9eb7 --region us-east-1 --bootstrap-version 10 --ssh-key prod-chef --identity-file ~/.ssh/prod-aws -c inf-knife.rb --platform debian
```

It turns out that the `--platform` flag defaults to `"omnibus"` and is handled independently of the `--bootstrap-version` flag logic.

Hope this helps!
