### ISSUE TITLE
omnibus fails to install?

### ISSUE THREAD

**Issue by sneak** [fnichol/knife-server#49]
firstmillion:chef▻ knife server bootstrap standalone -V --node-name chef.research.eeqj.de -H IP_REDACTED -i ~/.ssh/id_rsa --no-host-key-verify --ssh-user root
Bootstrapping Chef on IP_REDACTED
IP_REDACTED        Hostname is correct, so skipping...
IP_REDACTED 
IP_REDACTED -----> Downloading Chef Server package from http://www.opscode.com/chef/download-server?p=ubuntu&pv=13.10&m=x86_64&prerelease=false to /tmp/tmp.nRktFzkH/chef__amd64.deb
IP_REDACTED >>>>>> We encountered an error downloading the package.
IP_REDACTED 
IP_REDACTED 

Not exactly sure why it's doing this - wouldn't it be a better idea to use the omnibus script from Opscode's URL instead of bundling one with the knife-server?

**Comment by sneak** [comment]
I tried with -V also but it shows nothing more useful for troubleshooting.

**Comment by sneak** [comment]
Hrm, found '-l debug', and:

```
root@chef:~# wget -O /tmp/tmp.QxoNqaA6/chef__amd64.deb 'http://www.opscode.com/chef/download-server?p=ubuntu&pv=13.10&m=x86_64&prerelease=false'
--2014-01-26 19:30:30--  http://www.opscode.com/chef/download-server?p=ubuntu&pv=13.10&m=x86_64&prerelease=false
Resolving www.opscode.com (www.opscode.com)... 184.106.28.91
Connecting to www.opscode.com (www.opscode.com)|184.106.28.91|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2014-01-26 19:30:30 ERROR 404: Not Found.
```

Leaving off the arguments and just hitting http://www.opscode.com/chef/download-server gives a 500.

Is there a new/better URL for getting the server packages?

**Comment by arosenhagen** [comment]
URL to download of chef server has changed. It's now available on something like https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef-server_11.0.12-1.ubuntu.12.04_amd64.deb.

**Comment by fnichol** [comment]
It's possible that the Omnitruck API was having issues in January, but is back and functioning currently.

Since Opscode changed their name to Chef, I've updated the URL location to future-proof it as much as possible in f72f7cabe4530da67df1d873273fcc1482545d6a.

And finally, for anyone who has the specific package mirrored (or wishes to cherry pick), there is now a `--url` option which will override the Omnitruck API service logic as of 756cf01292b788274977b31af2aa8bbc26263f9d.

I'm going to cross fingers and close this out. If anyone's still having issues, then either re-open this or file a new issue.

Thank you all!
